### PR TITLE
Added FaceList API's and tests

### PR DESCRIPTION
**Pull request by irjudson**
New apis

### CODE REVIEW

**Comment by irjudson** [comment]
You're clearly not maintaining this from Amazon, feel free to give me the reigns.

**Comment by southwood** [comment]
I think @crwilcox was planning to fork this to https://github.com/Microsoft. I gave him control of https://pypi.python.org/pypi/projectoxford/. 

It looks like @zooba recently implemented a client for speech (https://github.com/zooba/projectoxford) and pushed an update to pypi. I don't see support for face / vision / emotion APIs yet, but the readme says contributions are welcome :)

@zooba, what is Microsoft's plan for this package going forward?

**Comment by zooba** [comment]
No plan right now - we're trying to negotiate with the team that owns the other language SDKs for Project Oxford to see if they'll take it, but it looks unlikely (of course, that will probably change once we start using it for awesome demos, but as long as it seems unpopular nobody wants to touch it :) )

Right now it's sitting in my own account because we consider it "sample code", and we'll get to the vision APIs sooner or later, but there are only unofficial devs on the library right now.

I'm also very keen to make it a much more fluent interface than what the regular APIs would suggest (Python has too many classes and too much camel-case already, IMHO).

**Comment by irjudson** [comment]
I'm more than a bit disappointed at our shotgun approach.

I've been working on the fork I have of Scotts code for awhile and It's in
good shape. I've built a bunch of tooling around it for partners, and am
supporting it actively.

It seems like we could do alot better job of sorting out our path forward
than we are.

--Ivan

Ivan R. Judson
irjudson.org
(425) 679-1375

**Comment by zooba** [comment]
Sure, I'll ping you internally.

**Comment by southwood** [comment]
@zooba, @irjudson, Let me know when you guys get something to replace this and I'll link to it in the readme and make it clear that this repo is deprecated.

**Pull request closed without merging**
